import fs from 'fs'
import path from 'path'
import { readLiveStories, getPresignedUrl } from '../../../lib/s3-storage'

/**
 * GET /api/content/published
 * Returns all published content from BOTH:
 * 1. data/stories.json (static, deployed with app)
 * 2. S3 stories-live.json (runtime-generated by cron)
 */

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  try {
    // Source 1: Static stories from deployed file
    const dbPath = path.join(process.cwd(), 'data', 'stories.json')
    const data = JSON.parse(await fs.promises.readFile(dbPath, 'utf8'))
    const staticStories = data.stories || []

    // Source 2: Live stories from S3 (generated by cron jobs)
    let liveStories = []
    try {
      liveStories = await readLiveStories()
    } catch (err) {
      console.warn('Could not load live stories from S3:', err.message)
    }

    // Merge both sources, deduplicate by id
    const allStories = [...liveStories, ...staticStories]
    const seenIds = new Set()
    const uniqueStories = allStories.filter(s => {
      if (seenIds.has(s.id)) return false
      seenIds.add(s.id)
      return true
    })

    // Filter only published/generated content with audio
    const published = await Promise.all(
      uniqueStories
        .filter(s => s.generated && (s.audioPath || s.audioUrl))
        .map(async story => {
          let audioPath = story.audioPath || story.audioUrl

          // If it's an S3 URL, generate a presigned URL (valid 6 hours)
          if (audioPath && (audioPath.includes('.s3.') || audioPath.includes('amazonaws.com'))) {
            try {
              audioPath = getPresignedUrl(audioPath)
            } catch (err) {
              console.warn('Presign failed for', story.title, err.message)
            }
          }

          // Presign thumbnail URL if it's on S3
          let thumbnailUrl = story.thumbnail || story.thumbnailUrl || ''
          if (thumbnailUrl && (thumbnailUrl.includes('.s3.') || thumbnailUrl.includes('amazonaws.com'))) {
            try {
              thumbnailUrl = getPresignedUrl(thumbnailUrl)
            } catch (err) {
              console.warn('Presign thumb failed for', story.title, err.message)
              thumbnailUrl = ''
            }
          }
          if (!thumbnailUrl) {
            thumbnailUrl = `https://via.placeholder.com/400x600/${getColorForCategory(story.category)}/ffffff?text=${story.emoji || '🎵'}`
          }

          return {
            id: story.id,
            title: story.title,
            description: story.description,
            category: story.category,
            language: story.language || 'Hindi',
            dialect: story.dialect,
            emoji: story.emoji,
            plays: story.plays,
            duration: story.duration,
            audioPath: audioPath,
            thumbnailUrl,
            new: story.new || false,
            generated: true,
            generatedAt: story.generatedAt || story.createdAt,
            autoGenerated: story.autoGenerated || false
          }
        })
    )

    const sorted = published.sort((a, b) => new Date(b.generatedAt || 0) - new Date(a.generatedAt || 0))

    res.status(200).json({
      success: true,
      content: sorted,
      total: sorted.length
    })

  } catch (error) {
    console.error('Error fetching published content:', error)
    res.status(500).json({
      error: 'Failed to load content',
      details: error.message
    })
  }
}

function getColorForCategory(category) {
  const colors = {
    'Romance': 'ff69b4',
    'Horror': '8b0000',
    'Thriller': '4b0082',
    'Comedy': 'ffd700',
    'Spiritual': '9370db',
    'Motivation': 'ff6347',
    'Tech': '00bfff',
    'Health': '32cd32',
    'Culture': 'e67e22',
    'Family': 'e91e63',
    'Drama': '9c27b0'
  }
  return colors[category] || '667eea'
}
